GET http://localhost:3003/api/blogs/
###

POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "My fourth new lame blog post.",
  "author": "Trotsky",
  "url": "http://trotsky.com",
  "likes": 10
}
###

GET http://localhost:3003/api/blogs/:id
###

DELETE http://localhost:3003/api/blogs/6435c0e1c1d925eaf32e3a61
###

PUT http://localhost:3003/api/blogs/643703fb5b98140e4e626ffe
Content-Type: application/json

{
  "title": "Update.",
  "author": "update",
  "url": "http://update.com",
  "likes": 10
}

