GET http://localhost:3003/api/blogs/
###

GET http://localhost:3003/
###

POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "My third awesome blog post.",
  "author": "Rosa Luxemburg",
  "url": "http://rosa.com",
  "likes": 8
}
###

GET http://localhost:3003/api/blogs/:id
###

DELETE http://localhost:3003/api/blogs/:id
###

PUT http://localhost:3003/api/blogs/:id
Content-Type: application/json

{
  "title": "My third awesome blog post.",
  "author": "Rosa Luxemburg",
  "url": "http://rosa-luxemburg.com",
  "likes": 10
}

