GET http://localhost:3003/api/blogs/
###

GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2giLCJpZCI6IjY0NjUyODliNGJkMTY3Nzk5MjIwMDVjZSIsImlhdCI6MTY4NDYxODQ3NCwiZXhwIjoxNjg0NjIyMDc0fQ.rC6Hu0_Xt4gBYa82OlgVllD-qSF5-0x-boRkncacxP4

{
  "title": "This is a test post that also belongs to Josh.",
  "author": "Josh",
  "url": "https://trotksy.com",
  "likes": 1
}
###


GET http://localhost:3003/api/blogs/:id
###

DELETE http://localhost:3003/api/blogs/:id
###

PUT http://localhost:3003/api/blogs/:id
Content-Type: application/json

{
  "title": "My third awesome blog post.",
  "author": "Rosa Luxemburg",
  "url": "http://rosa-luxemburg.com",
  "likes": 10
}

