GET http://localhost:3001/api/notes/
###

GET http://localhost:3001/api/notes/:id
###

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "Node.js is a backend JavaScript runtime environment.",
  "important": true
}