GET http://localhost:3001/api/notes/
###

GET http://localhost:3001/api/notes/:id
###

DELETE http://localhost:3001/api/notes/:id
###


POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "HTML is the bedrock of the web.",
  "important": true
}