GET http://localhost:3001/api/notes/
###

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "User id of the note creator is sent at the start along with the request.",
  "important": true,
  "userId": "645bf3c614d8acf03387fc1b"
}
###

GET http://localhost:3001/api/notes/:id
###

DELETE http://localhost:3001/api/notes/:id
###

PUT http://localhost:3001/api/notes/:id
Content-Type: application/json

{
  "content": "Some updated learning goal."
}
###
